### ISSUE TITLE
make modeler work with Safari browser

### ISSUE THREAD

**Issue by hofstef** [WPS/egon.io#10]
test for compatibility issues and fix them

**Comment by Mephisztoe** [comment]
So here comes a Mac user, right? I read you'd support Firefox and Chrome for the time being. If Microsoft didn't announce a week or so ago that they will suspend Edge, I had voted for that browser to be supported by your modeller. Rumor says, Microsoft will embed the chromium engine within their browser. Please keep that in mind for future releases.

**Comment by WanielDeiss** [comment]
Is this still up to date?
I did a smoke test with Safari 16.3 and it all seems to work

**Comment by AlexanderZellober** [comment]
We do not actively support Safari. If it currently works, that's great, however in the past the canvas sometimes did not correctly render items and the export of the domain story had parts missing. Our assumption was, that Safari's implementation of svg-rendering was slightly different from Chromium and Firefox and that that somehow broke the elementRegistry.
At some point we would like to actively support Safari, but we have no plans for that at the moment.
