### ISSUE TITLE
Port Code To Angular TS

### ISSUE THREAD

**Issue by AlexanderZellober** [WPS/egon.io#101]
For Version 2.0 we want to port the Code to Typescript and Angular to make it easier to create features that do not directly work with the modeler itself (i.e. autosave). The Code that interacts with the modeler will still be JS

###   Current TODOS for Angular Port:
Tasks:
- [x] Design: Optimising Toolbar
- [x] Design: Label-Dictionary
- [x] Design: Add Error-Dialogs
- [x] Dialogs: need functioning design
- [x] Icon Customization: Fix Functionality and replace design
- [x] Icon-Customization: Refactor loading of icons
- [x] Settings: general (i.e. autosave) settings need design
- [x] Label Dictionary: Fix Functionality 
- [x] Label Dictionary: Replace design
- [x] Replay: fix CSS for Buttons
- [x] Refactoring: Separate Presentation and Service Layers
- [x] Comment Code to make it understandable
- [x] Update ReadMe
- [x] Write Tests
- [x] rename GitHub Repository from 'domain-story-modeler' to 'egon.io'
- [x] rename 'master' to 'main'

Bugs:
- [x] Comments are not imported correctly
- [x] Groups are not exported correctly
- [x] Undo needs to be pressed 2 times to undo new Icons
- [x] Default Domain Configuration Button breaks domain
- [x] Autosave aplly does not work correctly
- [x] Import of .dst file (from v1.3.0) fails when it contains a custom icon: custom.name is undefined  addIconsToCss icon-dictionary.service.ts:273

**Comment by AlexanderZellober** [comment]
TODO: In the new Design of the Icon-Customization, the Action-Buttons are not yet User-friendly. Having the Save-Domain and the two reset Option Buttons between Buttons that work with the desktop-file system seems odd.

**Comment by hofstef** [comment]
v2 branch has been merged to main
