### ISSUE TITLE
Copy should also copy coloring

### ISSUE THREAD

**Issue by alexrjs** [WPS/egon.io#103]
**Is your feature request related to a problem? Please describe.**
When you copy an element, which was previously colored, it should also copy the color, so when you paste it you do not have to color the pasted elment newly.

**Describe the solution you'd like**
I color an actor with, say blue, then I copy this actor and paste it on a different place and it should be pasted blue not black, like the original actor.

**Describe alternatives you've considered**
There is no good alternative.

**Additional context**
For large stories you sometimes need the same element more often. E.g. a red Bug element, and it is very tedious to re-color each bug element red.

**Comment by hofstef** [comment]
Implemented with v2.0.1
