### ISSUE TITLE
improve rendering of sequence numbers

### ISSUE THREAD

**Issue by hofstef** [WPS/egon.io#107]
**Is your feature request related to a problem? Please describe.**
The blue circles around the sequence numbers does not look good if colored icons are used. Also, the circle is actually a "." and thus dependent on the font.

**Describe the solution you'd like**
The "circle" should be an actual circle or ellipse. The circle should not be filled and the outline of the circle should be black (like in the Domain Storytelling book).

**Comment by Geigerkind** [comment]
Done in v2.
