### ISSUE TITLE
'Replay' and 'Export ' buttons should not be enabled when canvas is empty

### ISSUE THREAD

**Issue by hofstef** [WPS/egon.io#111]
**Is your feature request related to a problem? Please describe.**
When I click Replay on an empty canvas, nothing happpens. 
When I click Export on an empty canvas, I get notified that there is nothing to export.

This behaviour is a bit annoying.

**Describe the solution you'd like**
Buttons should only be enabled if their actions can be applied. Therefore, Reply and Export should not be enabled when the canvas is empty.

**Comment by Geigerkind** [comment]
Done in v2.
