### ISSUE TITLE
Change default file ending for SVG export to .dst.svg

### ISSUE THREAD

**Issue by hschwentner** [WPS/egon.io#115]
**Is your feature request related to a problem? Please describe.**
When you see a file `foo.svg` you’ll know it’s an SVG file but you can only guess if it was exported by Egon.io and thus contains DST file metadata.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Make the default file ending for SVG exports .dst.svg instead of .svg similar to e.g. Draw.io. In the above example this would mean to have `foo.dst.svg`. It’s important not to use .svg.dst so other programs will still interpret the files as SVG.

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.]

**Additional context**
Draw.io stores by default in .drawio.svg files.

**Comment by hschwentner** [comment]
Was fixed in Version 1.2 or 1.3

**Comment by Geigerkind** [comment]
Done in v2.
