### ISSUE TITLE
Quality of Life Feature: Drag & Drop import for domain-stories

### ISSUE THREAD

**Issue by AlexanderZellober** [WPS/egon.io#118]
Importing the domain-story via the dedicated import Button can be tedious when switching between multiple domain stories. Enabling a drag&drop import on the canvas would fasten the workflow.  
Additionally the import of an icon-configuration can also be fastend by drag&drop in the configuration-window.

**Comment by hofstef** [comment]
Released with v2.1.0 - for now, only for Domain Stories (.egn, .dst, .egn.svg, .dst.svg).  Adding drag&drop to the icon customization seems less important but we might add it in the future.
