### ISSUE TITLE
Can not set color for text annotation

### ISSUE THREAD

**Issue by superbull** [WPS/egon.io#138]
**Describe the bug**
In the Figure 2.12 of the book "Domain Storytelling", it seems text annotation can be colored. But in v1.5.0, there is no way to change the color of a text annotation.

Figure 2.12 in the book:
![image](https://github.com/WPS/egon.io/assets/455630/8e1bb0b4-6670-4885-b3a0-fd4a8e1f4201)

Using v1.5.0 of egon.io:
![image](https://github.com/WPS/egon.io/assets/455630/9f921676-6144-44fd-8423-987c4616e510)

**Comment by hofstef** [comment]
Hi, you're right. Some diagrams in the book were altered in the production process of the book, e.g. to improve printability. 

I'll add this as a feature request. However, the stroke of text labels is thinner than the stroke of icons. That means some bright colors might work for icons, but become difficult to read when applied to annotations.
