### ISSUE TITLE
Applying colors could be improved

### ISSUE THREAD

**Issue by clecoentddd** [WPS/egon.io#140]
How to apply a color on an object is not user friendly on the desktop version (on the mobile app this is just perfect)

When opening the color palette, 16 or 24 colors would be enough then the experience should be identical as the mobile version

PS: I use egon on a daily basis for many different goals, just a great approach and tool!

**Comment by hofstef** [comment]
Hi, happy to read that you like using Egon.io! Which version are you currently using? Version 2.0 (currently in beta, see [https://egon.io/](https://egon.io/)), a new color picker is introduced. 

We don't actively support a mobile version of Egon.io. The modeling toolkit that provides the foundation for Egon - bpmn.io - works with mobile devices to some extent. However, they have dropped their support for touch devices recently. This means that Egon.io too will loose support for touch devices once we upgrade our dependencies.

**Comment by hofstef** [comment]
We've switched to a different color picker with v2.0.0-beta7. The color picker provides a consistent UI across browsers and comes with a predefined set of 12 colors. Since we will not backport this to v1.x.x. (soon to be deprecated), I think this issue is resolved.

**Comment by clecoentddd** [comment]
Thanks Stefan, yes it is easier now with the 12 predefined colors ! Thanks a lot !
