### ISSUE TITLE
Naming a narrative

### ISSUE THREAD

**Issue by clecoentddd** [WPS/egon.io#141]
When we build several narratives on a "page", could we have a way to name them using an object like "Narrative title" allowing text, resizing, coloring but not connected to any objects?

**Comment by clecoentddd** [comment]
Yes you are correct, in the attached file, I have named 2 narratives "HAPPY FLOW" and "CANCEL TRIP"
![Screenshot 2024-03-18 at 20 43 19](https://github.com/WPS/egon.io/assets/126658008/a9a0804f-6704-4a63-9f83-0ea7240b43e3)

Sometimes I have easily 7 to 8 narratives below each other.

**Comment by hofstef** [comment]
I agree that a visual overview of several Domain Stories is useful. I’ve been using Miro boards to achieve this (by exporting the Domain Stories as .svg and importing it to Miro). 

Egon.io was built with a simple “1 story = 1 model = 1 export file” approach. To implement a proper visual overview in Egon.io would take much more than adding a “narrative title”:

- Sequence numbers are meant to be consecutive (from 1 to n) for each story. If a second story is added to the same model, it should also start with 1 (and not n+1). The replay feature is also awkward to use if a story does not start at 1.
- There’s only one description field per model, which is probably not enough to document annotations and triggers of several stories.
- All stories would still be exported as one file. Which comes with drawbacks in file management (several people editing different stories simultaneously, diffing changes, …).

And that’s just from the top of my head. Considering all of that, I have to turn down your idea.
