### ISSUE TITLE
Egon.io behaves strange after uploading custom svg icon

### ISSUE THREAD

**Issue by cjjohansen** [WPS/egon.io#143]
**Describe the bug**

Egon.io behaves strange after uploading custom svg icon

Dragging the icon and connecting to it, behaves weird.

I can drag and use the standard icons, but not the cusomt ones that I uploaded

**To Reproduce**

I cannot see that I can expoer ta socalled .dts file

try to upload a .svg file will attach example if possible.

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
![DFDS_Icon_Truck_full_load_Square_Deep_Blue_RGB_01_2024](https://github.com/WPS/egon.io/assets/465656/8a1149b5-ec31-4ba3-adc9-90dad0d3b1bf)

![egon-io-custom-icons-not-draggable](https://github.com/WPS/egon.io/assets/465656/4eb2a902-e864-40bc-9d12-da98a6989287)

**Additional context**

Seems I wer eusing v2 beta. So not sure if it works in v1.

**Comment by cjjohansen** [comment]
Simply using v1 of Egon.IO and just uploading few icons or uploading one by one works fine.
Maybe the fact that I Bulk uploaded many icons could create an issue.
Uploading custom Icon in v2 beta or latest doesnt seem to work.
Get console errors
![image](https://github.com/WPS/egon.io/assets/465656/3fcc446f-b50e-405c-a8fe-934def04d71a)

**Comment by hofstef** [comment]
This issue should be solved in the [latest build](https://egon.io/app-latest/). To make sure your browser does not use a cached version, please delete the website data for egon.io in your browser (Chrome: In the URL bar, there's a button at the very left; then, click "Cookies and Wesite Data", "manage website data", and click on the trash bin icon. Finally, reload the website).

**Comment by hofstef** [comment]
solved in v2.0.0
