### ISSUE TITLE
Feature request: Add steps in between existing steps later

### ISSUE THREAD

**Issue by floriankraemer** [WPS/egon.io#145]
**Is your feature request related to a problem? Please describe.**

How can I add a new connection in between two steps when I already created more? Lets say I created step 1 to 5 and want to add one between 3 and 4 to get 6 in total, because something was forgotten in between. Either I don't know how to do it, to get the correct order of steps in the diagram or this is a missing feature.

**Describe the solution you'd like**

Maybe add a list of steps and show the active one, so that I can select it and it will add steps in between after that and re-order the enumeration of steps?

**Describe alternatives you've considered**

Redrawing the whole diagram, which is really annoying. :cry:

**Comment by hofstef** [comment]
Hi, this featre has been part of Egon since day one :-) I hope [this answers your question](https://egon.io/howto#naming-and-numbering-of-activities).

**Comment by floriankraemer** [comment]
Sorry, I don't get it. :worried: The button is not active no matter what I select. Yes, I've read that I can't select actors.

The button could also use a tooltip to show its function. And based on the icon I did not guess the function it has.

**Comment by hofstef** [comment]
Hi Florian, can you please provide more details?
- What browser are you using
- Which version of Egon.io are you using?
- Please attach a screenshot that illustrates the problem
- Please provide .dst/.egn file 
Thanks!

**Comment by floriankraemer** [comment]
Hey @hofstef , sorry for the late feedback. Better late than never. I was just stupid and missed the field in the dialog or didn't double click. Maybe add "Edit label" and "Change order" to the toolbox that opens when you single click on a connector? This would make it more obvious.
