### ISSUE TITLE
Creating overlapping groups breaks .egn and .egn.svg files

### ISSUE THREAD

**Issue by hofstef** [WPS/egon.io#158]
**Describe the bug**
Creating a group on top of another group breaks the export: The JSON contains the second group twice (with the same ID). This causes the import to fail.

This bug only happens when the second group is created while the mouse is within another group:

<img width="679" alt="overlapping-groups" src="https://github.com/user-attachments/assets/d7b66e32-16cf-42ec-942e-90fb4fab6771">

(the mouse cursor is not shown in this sceenshot, but you can see that the first group - named "1" - is highlighted because the mouse is hovering over it)

**To Reproduce**

1. Click on 'Group' in the palette and place it on the canvas.
2. Click on 'Group' in the palette and move the mouse so that the preview of the new group overlaps with the existing group and that the mouse cursor hovers over the first group.
3. Click on the canvas to create a second group that overlaps with the first one.
4. Export as .egn or .egn.svg
5. The JSON contains 3 groups: The first one, the second one and a duplicate of the second one. See for example attached file.
6. Import the .egn or egn.svg and open the browser console: The import will fail and stop after it has encountered the element with the duplicate ID.

![2 groups intersect a lot - broken egn](https://github.com/user-attachments/assets/632ad8f4-2c30-4940-9abb-c9a64d4d4b97)

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Version**

- Egon: v2.1.0
- Browser: Firefox, Chrome
- OS: Windows, MacOS

**Comment by DanielHeckert** [comment]
Should we repair the import for already broken  svg- or eng files regarding to the duplicates?

**Comment by hofstef** [comment]
fixed with v2.2.0
