### ISSUE TITLE
please make description of docker-based deployment more user-friendly

### ISSUE THREAD

**Issue by gernotstarke** [WPS/egon.io#187]
your documentation of getting and running the docker version lacks some details.

On my mac, several ways of trying to start the container failed.

* I suggest you provide a bash/shell/cmd script to both load and start everything required to get going.

* Please also point out the URL required in the browser (0.0.0.0 did not work for me, neither localhost)

* your image (as of November 25th 2024) is not available for Apple Silicon

**Comment by hofstef** [comment]
We've released a new version (v2.3.0) today and turned on a multi-plattform build for the Docker image. It should now work on Apple Silicon. It would be great if you could give us feedback.

The readme and [user guide](https://egon.io/howto#docker) now include the `docker run` command to run the container.  I don't think a script is needed for that.

**Comment by gernotstarke** [comment]
works now, thank you very much for the quick fix.

The message in the terminal might be a bit misleading, though.

Additionally, for non-experienced users you could add "navigate to 0.0.0.0:4040 in your browser", or similar.

<img width="731" alt="Screenshot 2024-11-27 um 12 19 05" src="https://github.com/user-attachments/assets/006a9eec-cbd5-4870-8d91-de43ef1d96e4">

**Comment by gernotstarke** [comment]
btw, awesome work you do here!! Providing egon free of charge is a real enabler for acceptance in many teams!

**Comment by gernotstarke** [comment]
that definitely was one of the quickest fixes in my (long) open-source history. Thanx.
