### ISSUE TITLE
Autosafe

### ISSUE THREAD

**Issue by kaischi69** [WPS/egon.io#64]
For reasons... I would love to have some kind of autosafe.

**Comment by almereyda** [comment]
This will be very useful, when a browser session is restarted after a reboot.

There may be various levels of auto-save, depending on availability and permissions:

- ~~Cookie~~
- Local Storage
- Session Storage (when granted, requires a Web Worker)

Given an eventual remote storage interface, auto-save could also take that into account.

**Comment by Geigerkind** [comment]
Done in v2.
