### ISSUE TITLE
Offer an option for non-stringified JSON on download to facilitate manual edits in code editors

### ISSUE THREAD

**Issue by CoeusCC** [WPS/egon.io#70]
**Is your feature request related to a problem? Please describe.**
As a developer I sometimes know what I want from the data itself even if there's not a clear way to do it through a UI. For example, the best way I've found to bulk delete objects is to create a large group and use it to basically "eat up" other objects then delete the group with its children.

The best use case I can think of is just being able read the file as a basic JSON object. I'm not sure how much space savings are realized in stringification, but most of my files are below 100K, and I think I'd gain more from reading the structure of the file than I do from the extra hard drive space saved.

Further, I'm getting into the habit of saving updated files to version control, so having everything on a separate line from a text editor is helpful to visualize changes in a diff. At the moment I'm only able to see to lines; one for "domain," and one for "dst." Beyond that it's hard for my git to highlight the specific parts that I've changed. I don't expect most people will be using it in this way, but the historic audit trail might be helpful.

**Describe the solution you'd like**
I think this could be added as a checkbox next to the export icon, or even as a flag in the settings screen. The only real difference would be a check to see if needs to be stringified, and maybe an additional parameter to let the parser know whether it was stringified or not for imports.

**Describe alternatives you've considered**
Exposing the object tree on the screen as a separate modal might offer the same benefits. Organizing objects by group/hierarchy, adding layers or groupings logically in the tree instead of visually on the page (I've worked a lot in Photoshop, so that's sort of where my mind is at), and other higher-order administrative features could negate the need for such a feature.

I'm really keen on version control for our current business needs, so anything that would allow this approach might hep address this feature as well. Since this is currently based primarily on browser downloads, I don't know what that might look like. Maybe some form of POSTing the JSON object to an endpoint that does further processing on it to handle the specifics that way.

**Additional context**
I've begun using this quite heavily in the past few weeks, and would be a significant beneficiary of any improvements. I'm happy to do a little more research and attempt to make a PR if it would be helpful. If that's desired I'd appreciate the opportunity to discuss the feature with the repository owners to make sure that it fits the long-term goals of the project, and to get a better idea of any design or architectural concerns they might have.

**Comment by hofstef** [comment]
We switched to strinigfied JSON as default with v2.0.0-beta some months ago. The file ending of the JSON file export was changed from .dst to .egn in order to reflect that the modeler is now called Egon.
